In [1]:
import tensorflow as tf
import numpy as np

## 1. 파일 하나 로드

In [2]:
xy = np.loadtxt("data-01-test-score.csv", delimiter=",", dtype=np.float32)

In [3]:
x_data = xy[:, :-1]
y_data = xy[:, -1]

In [4]:
print(x_data.shape)
print(x_data, len(x_data))

(25, 3)
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25


In [5]:
print(y_data.shape)
print(y_data, len(y_data))

(25,)
[152. 185. 180. 196. 142. 101. 149. 115. 175. 164. 141. 141. 184. 152.
 148. 192. 147. 183. 177. 159. 177. 175. 175. 149. 192.] 25


In [6]:
tf.model = tf.keras.Sequential()

Metal device set to: Apple M1 Pro


2023-03-12 22:52:55.238127: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-12 22:52:55.238241: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [7]:
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3))
tf.model.add(tf.keras.layers.Activation("linear"))

In [8]:
sgd = tf.keras.optimizers.SGD(1e-5)

In [9]:
tf.model.compile(loss="mse", optimizer=sgd)
tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
 activation (Activation)     (None, 1)                 0         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [10]:
history = tf.model.fit(x_data, y_data, epochs=2000)

Epoch 1/2000


2023-03-12 22:52:55.354817: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1/1 [==============================] - 0s 153ms/step - loss: 4087.7180
Epoch 2/2000
1/1 [==============================] - 0s 5ms/step - loss: 1559.7572
Epoch 3/2000
1/1 [==============================] - 0s 5ms/step - loss: 625.0616
Epoch 4/2000
1/1 [==============================] - 0s 7ms/step - loss: 279.4419
Epoch 5/2000
1/1 [==============================] - 0s 5ms/step - loss: 151.6191
Epoch 6/2000
1/1 [==============================] - 0s 8ms/step - loss: 104.3221
Epoch 7/2000


2023-03-12 22:52:55.452813: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 5ms/step - loss: 86.7975
Epoch 8/2000
1/1 [==============================] - 0s 7ms/step - loss: 80.2809
Epoch 9/2000
1/1 [==============================] - 0s 5ms/step - loss: 77.8342
Epoch 10/2000
1/1 [==============================] - 0s 5ms/step - loss: 76.8922
Epoch 11/2000
1/1 [==============================] - 0s 5ms/step - loss: 76.5067
Epoch 12/2000
1/1 [==============================] - 0s 5ms/step - loss: 76.3269
Epoch 13/2000
1/1 [==============================] - 0s 6ms/step - loss: 76.2232
Epoch 14/2000
1/1 [==============================] - 0s 5ms/step - loss: 76.1477
Epoch 15/2000
1/1 [==============================] - 0s 5ms/step - loss: 76.0826
Epoch 16/2000
1/1 [==============================] - 0s 6ms/step - loss: 76.0214
Epoch 17/2000
1/1 [==============================] - 0s 11ms/step - loss: 75.9617
Epoch 18/2000
1/1 [==============================] - 0s 6ms/step - loss: 75.9025
Epoch 19/2000
1/1 [========================

1/1 [==============================] - 0s 5ms/step - loss: 70.8100
Epoch 109/2000
1/1 [==============================] - 0s 5ms/step - loss: 70.7556
Epoch 110/2000
1/1 [==============================] - 0s 5ms/step - loss: 70.7013
Epoch 111/2000
1/1 [==============================] - 0s 5ms/step - loss: 70.6469
Epoch 112/2000
1/1 [==============================] - 0s 4ms/step - loss: 70.5927
Epoch 113/2000
1/1 [==============================] - 0s 4ms/step - loss: 70.5385
Epoch 114/2000
1/1 [==============================] - 0s 5ms/step - loss: 70.4843
Epoch 115/2000
1/1 [==============================] - 0s 5ms/step - loss: 70.4302
Epoch 116/2000
1/1 [==============================] - 0s 5ms/step - loss: 70.3761
Epoch 117/2000
1/1 [==============================] - 0s 5ms/step - loss: 70.3221
Epoch 118/2000
1/1 [==============================] - 0s 5ms/step - loss: 70.2682
Epoch 119/2000
1/1 [==============================] - 0s 4ms/step - loss: 70.2142
Epoch 120/2000
1/1 [===========

1/1 [==============================] - 0s 5ms/step - loss: 65.5956
Epoch 209/2000
1/1 [==============================] - 0s 5ms/step - loss: 65.5458
Epoch 210/2000
1/1 [==============================] - 0s 5ms/step - loss: 65.4959
Epoch 211/2000
1/1 [==============================] - 0s 5ms/step - loss: 65.4461
Epoch 212/2000
1/1 [==============================] - 0s 4ms/step - loss: 65.3963
Epoch 213/2000
1/1 [==============================] - 0s 5ms/step - loss: 65.3465
Epoch 214/2000
1/1 [==============================] - 0s 5ms/step - loss: 65.2968
Epoch 215/2000
1/1 [==============================] - 0s 5ms/step - loss: 65.2472
Epoch 216/2000
1/1 [==============================] - 0s 4ms/step - loss: 65.1976
Epoch 217/2000
1/1 [==============================] - 0s 5ms/step - loss: 65.1480
Epoch 218/2000
1/1 [==============================] - 0s 5ms/step - loss: 65.0985
Epoch 219/2000
1/1 [==============================] - 0s 5ms/step - loss: 65.0490
Epoch 220/2000
1/1 [===========

1/1 [==============================] - 0s 5ms/step - loss: 60.8108
Epoch 309/2000
1/1 [==============================] - 0s 5ms/step - loss: 60.7650
Epoch 310/2000
1/1 [==============================] - 0s 5ms/step - loss: 60.7192
Epoch 311/2000
1/1 [==============================] - 0s 6ms/step - loss: 60.6735
Epoch 312/2000
1/1 [==============================] - 0s 5ms/step - loss: 60.6278
Epoch 313/2000
1/1 [==============================] - 0s 5ms/step - loss: 60.5822
Epoch 314/2000
1/1 [==============================] - 0s 5ms/step - loss: 60.5366
Epoch 315/2000
1/1 [==============================] - 0s 5ms/step - loss: 60.4910
Epoch 316/2000
1/1 [==============================] - 0s 5ms/step - loss: 60.4455
Epoch 317/2000
1/1 [==============================] - 0s 5ms/step - loss: 60.4000
Epoch 318/2000
1/1 [==============================] - 0s 4ms/step - loss: 60.3545
Epoch 319/2000
1/1 [==============================] - 0s 5ms/step - loss: 60.3091
Epoch 320/2000
1/1 [===========

1/1 [==============================] - 0s 5ms/step - loss: 56.4196
Epoch 409/2000
1/1 [==============================] - 0s 5ms/step - loss: 56.3775
Epoch 410/2000
1/1 [==============================] - 0s 5ms/step - loss: 56.3355
Epoch 411/2000
1/1 [==============================] - 0s 5ms/step - loss: 56.2935
Epoch 412/2000
1/1 [==============================] - 0s 5ms/step - loss: 56.2516
Epoch 413/2000
1/1 [==============================] - 0s 5ms/step - loss: 56.2097
Epoch 414/2000
1/1 [==============================] - 0s 5ms/step - loss: 56.1678
Epoch 415/2000
1/1 [==============================] - 0s 4ms/step - loss: 56.1260
Epoch 416/2000
1/1 [==============================] - 0s 4ms/step - loss: 56.0843
Epoch 417/2000
1/1 [==============================] - 0s 4ms/step - loss: 56.0425
Epoch 418/2000
1/1 [==============================] - 0s 5ms/step - loss: 56.0008
Epoch 419/2000
1/1 [==============================] - 0s 4ms/step - loss: 55.9591
Epoch 420/2000
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 52.3891
Epoch 509/2000
1/1 [==============================] - 0s 5ms/step - loss: 52.3505
Epoch 510/2000
1/1 [==============================] - 0s 4ms/step - loss: 52.3119
Epoch 511/2000
1/1 [==============================] - 0s 5ms/step - loss: 52.2734
Epoch 512/2000
1/1 [==============================] - 0s 4ms/step - loss: 52.2349
Epoch 513/2000
1/1 [==============================] - 0s 4ms/step - loss: 52.1965
Epoch 514/2000
1/1 [==============================] - 0s 5ms/step - loss: 52.1580
Epoch 515/2000
1/1 [==============================] - 0s 5ms/step - loss: 52.1197
Epoch 516/2000
1/1 [==============================] - 0s 5ms/step - loss: 52.0813
Epoch 517/2000
1/1 [==============================] - 0s 5ms/step - loss: 52.0430
Epoch 518/2000
1/1 [==============================] - 0s 5ms/step - loss: 52.0047
Epoch 519/2000
1/1 [==============================] - 0s 5ms/step - loss: 51.9664
Epoch 520/2000
1/1 [===========

1/1 [==============================] - 0s 5ms/step - loss: 48.6893
Epoch 609/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.6539
Epoch 610/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.6185
Epoch 611/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.5831
Epoch 612/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.5478
Epoch 613/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.5125
Epoch 614/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.4772
Epoch 615/2000
1/1 [==============================] - 0s 4ms/step - loss: 48.4420
Epoch 616/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.4067
Epoch 617/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.3716
Epoch 618/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.3364
Epoch 619/2000
1/1 [==============================] - 0s 5ms/step - loss: 48.3013
Epoch 620/2000
1/1 [===========

1/1 [==============================] - 0s 5ms/step - loss: 45.2927
Epoch 709/2000
1/1 [==============================] - 0s 5ms/step - loss: 45.2602
Epoch 710/2000
1/1 [==============================] - 0s 5ms/step - loss: 45.2277
Epoch 711/2000
1/1 [==============================] - 0s 4ms/step - loss: 45.1952
Epoch 712/2000
1/1 [==============================] - 0s 5ms/step - loss: 45.1628
Epoch 713/2000
1/1 [==============================] - 0s 5ms/step - loss: 45.1304
Epoch 714/2000
1/1 [==============================] - 0s 4ms/step - loss: 45.0979
Epoch 715/2000
1/1 [==============================] - 0s 5ms/step - loss: 45.0656
Epoch 716/2000
1/1 [==============================] - 0s 4ms/step - loss: 45.0333
Epoch 717/2000
1/1 [==============================] - 0s 5ms/step - loss: 45.0010
Epoch 718/2000
1/1 [==============================] - 0s 4ms/step - loss: 44.9687
Epoch 719/2000
1/1 [==============================] - 0s 5ms/step - loss: 44.9365
Epoch 720/2000
1/1 [===========

1/1 [==============================] - 0s 5ms/step - loss: 42.1740
Epoch 809/2000
1/1 [==============================] - 0s 5ms/step - loss: 42.1442
Epoch 810/2000
1/1 [==============================] - 0s 4ms/step - loss: 42.1143
Epoch 811/2000
1/1 [==============================] - 0s 5ms/step - loss: 42.0845
Epoch 812/2000
1/1 [==============================] - 0s 5ms/step - loss: 42.0547
Epoch 813/2000
1/1 [==============================] - 0s 5ms/step - loss: 42.0250
Epoch 814/2000
1/1 [==============================] - 0s 5ms/step - loss: 41.9952
Epoch 815/2000
1/1 [==============================] - 0s 5ms/step - loss: 41.9655
Epoch 816/2000
1/1 [==============================] - 0s 4ms/step - loss: 41.9358
Epoch 817/2000
1/1 [==============================] - 0s 5ms/step - loss: 41.9062
Epoch 818/2000
1/1 [==============================] - 0s 5ms/step - loss: 41.8765
Epoch 819/2000
1/1 [==============================] - 0s 4ms/step - loss: 41.8469
Epoch 820/2000
1/1 [===========

1/1 [==============================] - 0s 5ms/step - loss: 39.3102
Epoch 909/2000
1/1 [==============================] - 0s 5ms/step - loss: 39.2827
Epoch 910/2000
1/1 [==============================] - 0s 5ms/step - loss: 39.2553
Epoch 911/2000
1/1 [==============================] - 0s 4ms/step - loss: 39.2280
Epoch 912/2000
1/1 [==============================] - 0s 5ms/step - loss: 39.2006
Epoch 913/2000
1/1 [==============================] - 0s 5ms/step - loss: 39.1733
Epoch 914/2000
1/1 [==============================] - 0s 4ms/step - loss: 39.1460
Epoch 915/2000
1/1 [==============================] - 0s 5ms/step - loss: 39.1187
Epoch 916/2000
1/1 [==============================] - 0s 5ms/step - loss: 39.0914
Epoch 917/2000
1/1 [==============================] - 0s 4ms/step - loss: 39.0642
Epoch 918/2000
1/1 [==============================] - 0s 5ms/step - loss: 39.0370
Epoch 919/2000
1/1 [==============================] - 0s 5ms/step - loss: 39.0098
Epoch 920/2000
1/1 [===========

Epoch 1008/2000
1/1 [==============================] - 0s 4ms/step - loss: 36.6800
Epoch 1009/2000
1/1 [==============================] - 0s 5ms/step - loss: 36.6548
Epoch 1010/2000
1/1 [==============================] - 0s 5ms/step - loss: 36.6296
Epoch 1011/2000
1/1 [==============================] - 0s 4ms/step - loss: 36.6045
Epoch 1012/2000
1/1 [==============================] - 0s 4ms/step - loss: 36.5794
Epoch 1013/2000
1/1 [==============================] - 0s 4ms/step - loss: 36.5543
Epoch 1014/2000
1/1 [==============================] - 0s 4ms/step - loss: 36.5292
Epoch 1015/2000
1/1 [==============================] - 0s 5ms/step - loss: 36.5041
Epoch 1016/2000
1/1 [==============================] - 0s 5ms/step - loss: 36.4791
Epoch 1017/2000
1/1 [==============================] - 0s 4ms/step - loss: 36.4541
Epoch 1018/2000
1/1 [==============================] - 0s 4ms/step - loss: 36.4291
Epoch 1019/2000
1/1 [==============================] - 0s 5ms/step - loss: 36.4041
Epoc

1/1 [==============================] - 0s 4ms/step - loss: 34.3104
Epoch 1107/2000
1/1 [==============================] - 0s 5ms/step - loss: 34.2873
Epoch 1108/2000
1/1 [==============================] - 0s 5ms/step - loss: 34.2641
Epoch 1109/2000
1/1 [==============================] - 0s 5ms/step - loss: 34.2410
Epoch 1110/2000
1/1 [==============================] - 0s 5ms/step - loss: 34.2178
Epoch 1111/2000
1/1 [==============================] - 0s 5ms/step - loss: 34.1947
Epoch 1112/2000
1/1 [==============================] - 0s 4ms/step - loss: 34.1717
Epoch 1113/2000
1/1 [==============================] - 0s 4ms/step - loss: 34.1486
Epoch 1114/2000
1/1 [==============================] - 0s 5ms/step - loss: 34.1255
Epoch 1115/2000
1/1 [==============================] - 0s 5ms/step - loss: 34.1025
Epoch 1116/2000
1/1 [==============================] - 0s 5ms/step - loss: 34.0795
Epoch 1117/2000
1/1 [==============================] - 0s 5ms/step - loss: 34.0565
Epoch 1118/2000
1/1 

1/1 [==============================] - 0s 5ms/step - loss: 32.1299
Epoch 1205/2000
1/1 [==============================] - 0s 4ms/step - loss: 32.1086
Epoch 1206/2000
1/1 [==============================] - 0s 5ms/step - loss: 32.0872
Epoch 1207/2000
1/1 [==============================] - 0s 5ms/step - loss: 32.0660
Epoch 1208/2000
1/1 [==============================] - 0s 4ms/step - loss: 32.0446
Epoch 1209/2000
1/1 [==============================] - 0s 5ms/step - loss: 32.0234
Epoch 1210/2000
1/1 [==============================] - 0s 5ms/step - loss: 32.0022
Epoch 1211/2000
1/1 [==============================] - 0s 5ms/step - loss: 31.9809
Epoch 1212/2000
1/1 [==============================] - 0s 5ms/step - loss: 31.9597
Epoch 1213/2000
1/1 [==============================] - 0s 5ms/step - loss: 31.9386
Epoch 1214/2000
1/1 [==============================] - 0s 5ms/step - loss: 31.9174
Epoch 1215/2000
1/1 [==============================] - 0s 5ms/step - loss: 31.8962
Epoch 1216/2000
1/1 

1/1 [==============================] - 0s 5ms/step - loss: 30.1230
Epoch 1303/2000
1/1 [==============================] - 0s 5ms/step - loss: 30.1034
Epoch 1304/2000
1/1 [==============================] - 0s 5ms/step - loss: 30.0837
Epoch 1305/2000
1/1 [==============================] - 0s 5ms/step - loss: 30.0642
Epoch 1306/2000
1/1 [==============================] - 0s 5ms/step - loss: 30.0446
Epoch 1307/2000
1/1 [==============================] - 0s 5ms/step - loss: 30.0250
Epoch 1308/2000
1/1 [==============================] - 0s 5ms/step - loss: 30.0055
Epoch 1309/2000
1/1 [==============================] - 0s 5ms/step - loss: 29.9859
Epoch 1310/2000
1/1 [==============================] - 0s 4ms/step - loss: 29.9664
Epoch 1311/2000
1/1 [==============================] - 0s 4ms/step - loss: 29.9469
Epoch 1312/2000
1/1 [==============================] - 0s 5ms/step - loss: 29.9274
Epoch 1313/2000
1/1 [==============================] - 0s 4ms/step - loss: 29.9080
Epoch 1314/2000
1/1 

1/1 [==============================] - 0s 5ms/step - loss: 28.2757
Epoch 1401/2000
1/1 [==============================] - 0s 5ms/step - loss: 28.2577
Epoch 1402/2000
1/1 [==============================] - 0s 6ms/step - loss: 28.2396
Epoch 1403/2000
1/1 [==============================] - 0s 5ms/step - loss: 28.2216
Epoch 1404/2000
1/1 [==============================] - 0s 5ms/step - loss: 28.2035
Epoch 1405/2000
1/1 [==============================] - 0s 6ms/step - loss: 28.1855
Epoch 1406/2000
1/1 [==============================] - 0s 5ms/step - loss: 28.1675
Epoch 1407/2000
1/1 [==============================] - 0s 6ms/step - loss: 28.1495
Epoch 1408/2000
1/1 [==============================] - 0s 5ms/step - loss: 28.1316
Epoch 1409/2000
1/1 [==============================] - 0s 5ms/step - loss: 28.1136
Epoch 1410/2000
1/1 [==============================] - 0s 6ms/step - loss: 28.0957
Epoch 1411/2000
1/1 [==============================] - 0s 5ms/step - loss: 28.0777
Epoch 1412/2000
1/1 

1/1 [==============================] - 0s 5ms/step - loss: 26.5751
Epoch 1499/2000
1/1 [==============================] - 0s 5ms/step - loss: 26.5584
Epoch 1500/2000
1/1 [==============================] - 0s 6ms/step - loss: 26.5418
Epoch 1501/2000
1/1 [==============================] - 0s 5ms/step - loss: 26.5252
Epoch 1502/2000
1/1 [==============================] - 0s 5ms/step - loss: 26.5086
Epoch 1503/2000
1/1 [==============================] - 0s 6ms/step - loss: 26.4920
Epoch 1504/2000
1/1 [==============================] - 0s 5ms/step - loss: 26.4754
Epoch 1505/2000
1/1 [==============================] - 0s 6ms/step - loss: 26.4589
Epoch 1506/2000
1/1 [==============================] - 0s 5ms/step - loss: 26.4424
Epoch 1507/2000
1/1 [==============================] - 0s 5ms/step - loss: 26.4258
Epoch 1508/2000
1/1 [==============================] - 0s 6ms/step - loss: 26.4093
Epoch 1509/2000
1/1 [==============================] - 0s 5ms/step - loss: 26.3928
Epoch 1510/2000
1/1 

1/1 [==============================] - 0s 5ms/step - loss: 25.0092
Epoch 1597/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.9939
Epoch 1598/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.9785
Epoch 1599/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.9632
Epoch 1600/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.9480
Epoch 1601/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.9327
Epoch 1602/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.9174
Epoch 1603/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.9022
Epoch 1604/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.8870
Epoch 1605/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.8717
Epoch 1606/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.8565
Epoch 1607/2000
1/1 [==============================] - 0s 5ms/step - loss: 24.8414
Epoch 1608/2000
1/1 

1/1 [==============================] - 0s 6ms/step - loss: 23.5672
Epoch 1695/2000
1/1 [==============================] - 0s 5ms/step - loss: 23.5531
Epoch 1696/2000
1/1 [==============================] - 0s 8ms/step - loss: 23.5389
Epoch 1697/2000
1/1 [==============================] - 0s 6ms/step - loss: 23.5249
Epoch 1698/2000
1/1 [==============================] - 0s 5ms/step - loss: 23.5108
Epoch 1699/2000
1/1 [==============================] - 0s 6ms/step - loss: 23.4967
Epoch 1700/2000
1/1 [==============================] - 0s 6ms/step - loss: 23.4827
Epoch 1701/2000
1/1 [==============================] - 0s 6ms/step - loss: 23.4686
Epoch 1702/2000
1/1 [==============================] - 0s 6ms/step - loss: 23.4546
Epoch 1703/2000
1/1 [==============================] - 0s 6ms/step - loss: 23.4406
Epoch 1704/2000
1/1 [==============================] - 0s 5ms/step - loss: 23.4266
Epoch 1705/2000
1/1 [==============================] - 0s 5ms/step - loss: 23.4126
Epoch 1706/2000
1/1 

1/1 [==============================] - 0s 5ms/step - loss: 22.2390
Epoch 1793/2000
1/1 [==============================] - 0s 5ms/step - loss: 22.2260
Epoch 1794/2000
1/1 [==============================] - 0s 5ms/step - loss: 22.2130
Epoch 1795/2000
1/1 [==============================] - 0s 5ms/step - loss: 22.2000
Epoch 1796/2000
1/1 [==============================] - 0s 5ms/step - loss: 22.1871
Epoch 1797/2000
1/1 [==============================] - 0s 5ms/step - loss: 22.1741
Epoch 1798/2000
1/1 [==============================] - 0s 5ms/step - loss: 22.1612
Epoch 1799/2000
1/1 [==============================] - 0s 5ms/step - loss: 22.1482
Epoch 1800/2000
1/1 [==============================] - 0s 5ms/step - loss: 22.1353
Epoch 1801/2000
1/1 [==============================] - 0s 4ms/step - loss: 22.1224
Epoch 1802/2000
1/1 [==============================] - 0s 5ms/step - loss: 22.1095
Epoch 1803/2000
1/1 [==============================] - 0s 5ms/step - loss: 22.0966
Epoch 1804/2000
1/1 

1/1 [==============================] - 0s 5ms/step - loss: 21.0155
Epoch 1891/2000
1/1 [==============================] - 0s 5ms/step - loss: 21.0035
Epoch 1892/2000
1/1 [==============================] - 0s 5ms/step - loss: 20.9915
Epoch 1893/2000
1/1 [==============================] - 0s 5ms/step - loss: 20.9796
Epoch 1894/2000
1/1 [==============================] - 0s 5ms/step - loss: 20.9676
Epoch 1895/2000
1/1 [==============================] - 0s 4ms/step - loss: 20.9557
Epoch 1896/2000
1/1 [==============================] - 0s 5ms/step - loss: 20.9438
Epoch 1897/2000
1/1 [==============================] - 0s 5ms/step - loss: 20.9318
Epoch 1898/2000
1/1 [==============================] - 0s 5ms/step - loss: 20.9199
Epoch 1899/2000
1/1 [==============================] - 0s 5ms/step - loss: 20.9081
Epoch 1900/2000
1/1 [==============================] - 0s 5ms/step - loss: 20.8962
Epoch 1901/2000
1/1 [==============================] - 0s 5ms/step - loss: 20.8843
Epoch 1902/2000
1/1 

1/1 [==============================] - 0s 5ms/step - loss: 19.8882
Epoch 1989/2000
1/1 [==============================] - 0s 5ms/step - loss: 19.8771
Epoch 1990/2000
1/1 [==============================] - 0s 5ms/step - loss: 19.8661
Epoch 1991/2000
1/1 [==============================] - 0s 5ms/step - loss: 19.8551
Epoch 1992/2000
1/1 [==============================] - 0s 5ms/step - loss: 19.8441
Epoch 1993/2000
1/1 [==============================] - 0s 6ms/step - loss: 19.8331
Epoch 1994/2000
1/1 [==============================] - 0s 5ms/step - loss: 19.8221
Epoch 1995/2000
1/1 [==============================] - 0s 5ms/step - loss: 19.8111
Epoch 1996/2000
1/1 [==============================] - 0s 5ms/step - loss: 19.8002
Epoch 1997/2000
1/1 [==============================] - 0s 4ms/step - loss: 19.7892
Epoch 1998/2000
1/1 [==============================] - 0s 5ms/step - loss: 19.7782
Epoch 1999/2000
1/1 [==============================] - 0s 5ms/step - loss: 19.7673
Epoch 2000/2000
1/1 

In [11]:
# Ask my score
print("Your score will be ", tf.model.predict([[100, 70, 101]]))

print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))

1/1 [==============================] - 0s 40ms/step
Your score will be  [[179.88103]]
1/1 [==============================] - 0s 17ms/step
Other scores will be  [[152.13847]
 [186.29674]]


2023-03-12 22:53:07.825462: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


## 2. 파일 여러개 로드